Update shiftr
I think I'm there. It helped me ad flags and options and check variables first, and also request them at the command line

diff --git a/shiftr b/shiftr
--- a/shiftr
+++ b/shiftr
@@ -1,10 +1,45 @@
 #!/bin/bash
 
 # Set up variables
-ext1="jpg"
-ext2="mp4"
-source_dir="/path/to/source"
-dest_dir="/path/to/destination"
+ext1=""
+ext2=""
+source_dir=""
+dest_dir=""
+
+# Parse command line options
+while getopts ":e:s:d:" opt; do
+  case $opt in
+    e)
+      ext1=$OPTARG
+      ext2=$OPTARG
+      ;;
+    s)
+      source_dir=$OPTARG
+      ;;
+    d)
+      dest_dir=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+# Check if variables are set
+if [ -z "$ext1" ] || [ -z "$ext2" ] || [ -z "$source_dir" ] || [ -z "$dest_dir" ]; then
+  # Print message to console
+  echo "Variables are not set, asking you to provide them"
+  # Prompt user to enter values for variables
+  read -p "Enter value for ext1: " ext1
+  read -p "Enter value for ext2: " ext2
+  read -p "Enter value for source_dir: " source_dir
+  read -p "Enter value for dest_dir: " dest_dir
+fi
 
 # Function to extract date and time from filename
 extract_datetime() {
@@ -25,70 +60,36 @@ extract_datetime() {
 
 # Function to construct destination path
 construct_path() {
-  # Use date and time variables to construct destination path
-  dest_path="$dest_dir/$year/${year:2}-$month/$year-$month-$day/$filename"
-  # Return destination path
-  echo "$dest_path"
-}
-
-# Function to move file
-move_file() {
-  # Use rsync to move file to destination path
-  if rsync -a "$file" "$dest_path"; then
-    # Print success message
-    echo "Success: Moved $file to $dest_path"
-  else
-    # Print error message
-    echo "Error: Unable to move $file to $dest_path"
-  fi
-}
-
-# Set up command line options
-
-# Option to show usage message
-if [ "$1" == "-h" ]; then
-  echo "Usage: $(basename $0) [-n] [-q]"
-  echo "Sort and move files with YYYYMMDD_hh:mm:ss.extension format to destination directory"
-  echo "  -n  Dry run/test mode"
-  echo "  -q  Quiet mode"
-  exit 0
-fi
-
-# Option to run in test/dry run mode
-if [ "$1" == "-n" ]; then
-  test_mode=true
-  shift
-fi
-
-# Option to run quietly
-if [ "$1" == "-q" ]; then
-  quiet_mode=true
-  shift
-fi
-
-# Loop through files in source directory
-for file in "$source_dir"/*; do
-  # Extract filename and file extension
-  filename=$(basename "$file")
-  extension="${filename##*.}"
-  # If file extension is not ext1 or ext2, skip file
-  if [ "$extension" != "$ext1" ] && [ "$extension" != "$ext2" ]; then
-    continue
-  fi
   # Extract date and time from filename
   extract_datetime
-  # Construct destination path
-  dest_path=$(construct_path)
-  # If not in test mode, move file
-  if [ -z "$test_mode" ]; then
-    move_file
-  # Print dry run message if in test mode
+  if [ $? -eq 0 ]; then
+    # Construct destination path using date and time from filename
+    dest_path="$dest_dir/$year/${year:2:2}-$month/$year-$month-$day"
   else
-    echo "Dry run: Would have moved $file to $dest_path"
+    # Print error message if unable to extract date and time from filename
+    echo "Error: Unable to construct destination path"
+    return 1
   fi
-  # Print success or error message if not in quiet mode
-  if [ -z "$quiet_mode" ]; then
-    echo "$message"
+}
+
+# Iterate over files in source directory
+for file in "$source_dir"/*; do
+  filename=$(basename "$file")
+  extension="${filename##*.}"
+  # Check if file is of correct type
+  if [ "$extension" == "$ext1" ] || [ "$extension" == "$ext2" ]; then
+    # Construct destination path
+    construct_path
+    if [ $? -eq 0 ]; then
+      # Check if destination directory exists
+      if [ ! -d "$dest_path" ]; then
+        # Create destination directory if it does not exist
+        mkdir -p "$dest_path"
+      fi
+      # Move file to destination directory
+      mv "$file" "$dest_path/$filename"
+      # Print success message
+      echo "Success: Moved $filename to $dest_path"
+    fi
   fi
 done
-
